/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mestredebatalha;
import javax.swing.JOptionPane;
/**
 *
 * @author Mariana Brito
 */
public class Modo_de_jogo extends javax.swing.JFrame {
    int jogo;
    

    /**
     * Creates new form Modo_de_jogo
     */
    public Modo_de_jogo() {
        initComponents();
        setSize(1000,800);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modo_jogo = new javax.swing.JLabel();
        war = new javax.swing.JToggleButton();
        x1 = new javax.swing.JToggleButton();
        seleciona_jogador = new javax.swing.JLabel();
        guerra = new javax.swing.JLabel();
        luta = new javax.swing.JLabel();
        jogador_2 = new javax.swing.JLabel();
        computador = new javax.swing.JLabel();
        jogador_2_botao = new javax.swing.JToggleButton();
        computador_botao = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        modo_jogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/titulo.png"))); // NOI18N
        modo_jogo.setText("jLabel1");
        getContentPane().add(modo_jogo);
        modo_jogo.setBounds(680, 30, 200, 30);

        war.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/war.png"))); // NOI18N
        war.setBorderPainted(false);
        war.setContentAreaFilled(false);
        war.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        war.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warActionPerformed(evt);
            }
        });
        getContentPane().add(war);
        war.setBounds(590, 90, 100, 100);

        x1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/x1.png"))); // NOI18N
        x1.setBorderPainted(false);
        x1.setContentAreaFilled(false);
        x1.setFocusPainted(false);
        x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1ActionPerformed(evt);
            }
        });
        getContentPane().add(x1);
        x1.setBounds(860, 90, 100, 100);

        seleciona_jogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/seleciona_jogador.png"))); // NOI18N
        getContentPane().add(seleciona_jogador);
        seleciona_jogador.setBounds(650, 240, 250, 56);

        guerra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/guerra.png"))); // NOI18N
        getContentPane().add(guerra);
        guerra.setBounds(510, 190, 190, 30);

        luta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/luta.png"))); // NOI18N
        getContentPane().add(luta);
        luta.setBounds(790, 190, 220, 30);

        jogador_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/jogador_2.png"))); // NOI18N
        getContentPane().add(jogador_2);
        jogador_2.setBounds(500, 410, 200, 30);

        computador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/computador.png"))); // NOI18N
        getContentPane().add(computador);
        computador.setBounds(780, 410, 200, 30);

        jogador_2_botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/player2.png"))); // NOI18N
        jogador_2_botao.setBorderPainted(false);
        jogador_2_botao.setContentAreaFilled(false);
        jogador_2_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogador_2_botaoActionPerformed(evt);
            }
        });
        getContentPane().add(jogador_2_botao);
        jogador_2_botao.setBounds(580, 310, 100, 100);

        computador_botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/pc.png"))); // NOI18N
        computador_botao.setContentAreaFilled(false);
        computador_botao.setDoubleBuffered(true);
        computador_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computador_botaoActionPerformed(evt);
            }
        });
        getContentPane().add(computador_botao);
        computador_botao.setBounds(840, 310, 133, 100);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/avançar.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(690, 510, 190, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mestredebatalha/5345_other_hd_wallpapers_knight_sword.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1020, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void warActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warActionPerformed
         jogo=1;
    }//GEN-LAST:event_warActionPerformed

    private void x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1ActionPerformed
       jogo=4;
    }//GEN-LAST:event_x1ActionPerformed

    private void jogador_2_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogador_2_botaoActionPerformed
        jogo=jogo+3;
    }//GEN-LAST:event_jogador_2_botaoActionPerformed

    private void computador_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computador_botaoActionPerformed
        jogo=jogo+4;
    }//GEN-LAST:event_computador_botaoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jogo==4)
        {
            JOptionPane.showMessageDialog(null,"Guerra entre 2 jogadores confirmada!","Modo de Jogo",JOptionPane.INFORMATION_MESSAGE);
            new Selecao_de_tropas1().setVisible(true);
            this.dispose();
        }
        else
        {
            if(jogo==5)
        {
            JOptionPane.showMessageDialog(null,"Guerra entre jogador e computador confirmada!","Modo de Jogo",JOptionPane.INFORMATION_MESSAGE);
            new Selecao_de_tropas1().setVisible(true);
            this.dispose();
        }
            else
        {
            if(jogo==7)
        {
            JOptionPane.showMessageDialog(null,"Luta entre 2 jogadores confirmada!","Modo de Jogo",JOptionPane.INFORMATION_MESSAGE);
            new Selecao_de_campeoes().setVisible(true);
            this.dispose();
        }
            else
        {
            if(jogo==8)
        {
            JOptionPane.showMessageDialog(null,"Luta entre jogador e computador confirmada!","Modo de Jogo",JOptionPane.INFORMATION_MESSAGE);
            new Selecao_de_campeoes().setVisible(true);
            this.dispose();
        }
        }
        }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modo_de_jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modo_de_jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modo_de_jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modo_de_jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modo_de_jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel computador;
    private javax.swing.JToggleButton computador_botao;
    private javax.swing.JLabel guerra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jogador_2;
    private javax.swing.JToggleButton jogador_2_botao;
    private javax.swing.JLabel luta;
    private javax.swing.JLabel modo_jogo;
    private javax.swing.JLabel seleciona_jogador;
    private javax.swing.JToggleButton war;
    private javax.swing.JToggleButton x1;
    // End of variables declaration//GEN-END:variables
}
